# Použijeme Node.js 18
FROM node:18-alpine

# Pracovní adresář v kontejneru
WORKDIR /app

# Zkopíruj package.json a nainstaluj závislosti
COPY package.json package-lock.json ./
RUN npm ci --only=production

# Zkopíruj projekt a buildni
COPY . .
RUN npm run build

# Spuštění Strapi
CMD ["npm", "start"]